version: '3'
services:
    mongo:
        image: 'mongo'
        container_name: 'mvp-mongo'
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - /data/db
        ports:
            - 27017:27017  
    api:
        build: ../mvp-api/
        container_name: 'mvp-api'
        ports:
            - "3000:3000"
    web:
        build: ../mvp-web/
        container_name: 'mvp-web'
        ports:
            - "8080:8080"