version: '3'
services:
    database:
        image: 'mongo'
        container_name: 'mvp-mongo'
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - /data/db
        ports:
            - 27017:27017  
    web:
        build: ../mvp-api/
        ports:
            - "3000:3000"